Убрать упоминания регулярных выражений из настроек списка разрешенных доменов
evotor/documentation pull request #11
Opened 2017-12-04 14:44 UTC by notxcain

Теперь документация предлагает указывать протокол домен и опциональный кастомный порт.

Наверное стоит добавить пример с IP адресом, пушну в следующем коммите.

2017-12-04 14:55 UTC, e-v-petrov submitted a review, later dismissed

2017-12-04 14:58 UTC, Lytkini requested changes
Вот тут скобки не нужны:
"и укажите список доменов (или IP-адресов) с указанием протокола"

В остальном всё ок.
Вопрос. Я могу это как-то сам прямо в коммите поправить?

2017-12-04 15:24 UTC, notxcain commented
@Lytkini поправил. Редактировать должен мочь, просто нажимай на иконку карандаша

2017-12-04 16:14 UTC, a8t3r commented on pages/evotordoc/java_SDK/doc_java_third_party_service_communication.md
> +* `http://162.242.239.16`
Думаю, нужно отдельно указать:
* схема обязательна - без схемы работать не будет.
* https://example.com и http://example.com - это разные адреса

2017-12-05 08:37 UTC, Lytkini approved these changes

2018-01-30 12:55 UTC, merged