React Native SDK Documentation
evotor/documentation pull request #16
Opened 2018-02-09 15:05 UTC by Lytkini

Закончил работу над RN SDK. Этот PR обновляет только md файлы, посмотреть как это будет выглядеть в доке можно у меня:
https://lytkini.github.io/jekyll/doc_react_gettingstarted.html

Если всё ок, отдельным PR обновлю html-файлы, которые обновят доку на сайте.
В ревьюеры надо бы добавить Андрея Кузнецова, Артёма Лунькова и Илью Линника. У меня почему-то они в списке ревьюеров не появляются.

2018-02-12 10:34 UTC, xcam commented on pages/evotordoc/React_SDK/doc_react_generatingsignedapk.md
> +2. В поле `app_uuid` элемента `<meta-data>` вместо текущего идентификатора укажите идентификатор приложения, который вы получили в [процессе подготовки приложения на сайте разработчиков](./doc_java_a
У меня нет такого элемента в AndroidManifest. Нужно описать в какое место его добавить

2018-02-12 10:38 UTC, xcam commented on pages/evotordoc/React_SDK/doc_react_gettingstarted.md
> +2. В поле `app_uuid` элемента `<meta-data>` вместо текущего идентификатора укажите идентификатор приложения, который вы получили в [процессе подготовки приложения на сайте разработчиков](./doc_java_a
У меня нет такого элемента в AndroidManifest. Нужно описать в какое место его добавить

2018-02-12 10:39 UTC, xcam commented on pages/evotordoc/React_SDK/doc_react_gettingstarted.md
> +tags: [terminal, react]
На странице с документацией вижу только terminal почему-то

2018-02-12 10:42 UTC, xcam commented on pages/evotordoc/React_SDK/doc_react_gettingstarted.md
> +   react-native run-Android
react-native run-**a**ndroid

2018-02-12 12:26 UTC, Lytkini commented on pages/evotordoc/React_SDK/doc_react_gettingstarted.md
> +   react-native run-Android
+

2018-02-12 12:47 UTC, xcam requested changes
Нужны доработки

2018-02-13 08:07 UTC, xcam commented on pages/evotordoc/React_SDK/doc_react_gettingstarted.md
> +1. В файле `YourAppName\android\build.gradle` измените следующие параметры:
у меня путь другой YourAppName\android\**app\**build.gradle

2018-02-13 08:10 UTC, xcam commented on pages/evotordoc/React_SDK/doc_react_gettingstarted.md
> +1. В Android Studio откройте манифест приложения, размещённый по адресу `YourAppName\android\app\src\AndroidManifest.xml`.
у меня путь другой YourAppName\android\app\src\ **main** \AndroidManifest.xml

2018-02-13 08:11 UTC, xcam commented on pages/evotordoc/React_SDK/doc_react_gettingstarted.md
> +   minSdkVersion 22
В AndroidManifest у меня добавились строчки
<uses-sdk
        android:minSdkVersion="16"
        android:targetSdkVersion="22" />

В нем править этот параметр не надо?

2018-02-13 08:16 UTC, Lytkini commented on pages/evotordoc/React_SDK/doc_react_gettingstarted.md
> +1. В файле `YourAppName\android\build.gradle` измените следующие параметры:
\+

2018-02-13 08:17 UTC, Lytkini commented on pages/evotordoc/React_SDK/doc_react_gettingstarted.md
> +1. В Android Studio откройте манифест приложения, размещённый по адресу `YourAppName\android\app\src\AndroidManifest.xml`.
\+

2018-02-13 08:18 UTC, Lytkini commented on pages/evotordoc/React_SDK/doc_react_generatingsignedapk.md
> +2. В поле `app_uuid` элемента `<meta-data>` вместо текущего идентификатора укажите идентификатор приложения, который вы получили в [процессе подготовки приложения на сайте разработчиков](./doc_java_a
\+

2018-02-13 08:18 UTC, Lytkini commented on pages/evotordoc/React_SDK/doc_react_gettingstarted.md
> +2. В поле `app_uuid` элемента `<meta-data>` вместо текущего идентификатора укажите идентификатор приложения, который вы получили в [процессе подготовки приложения на сайте разработчиков](./doc_java_a
\+

2018-02-13 08:24 UTC, Lytkini commented on pages/evotordoc/React_SDK/doc_react_gettingstarted.md
> +tags: [terminal, react]
/+

2018-02-13 08:30 UTC, xcam commented on pages/evotordoc/React_SDK/doc_react_gettingstarted.md
> +   react-native run-android
Получил ошибку по итогу
![screenshot_20180213-111710](https://user-images.githubusercontent.com/5175891/36140171-52fda4dc-10b1-11e8-801d-e6069573d0fe.png)

2018-02-13 08:31 UTC, xcam requested changes
Есть замечания

2018-02-13 08:35 UTC, Lytkini commented on pages/evotordoc/React_SDK/doc_react_gettingstarted.md
> +   minSdkVersion 22
\+

2018-02-13 11:28 UTC, Lytkini commented on pages/evotordoc/React_SDK/doc_react_gettingstarted.md
> +   react-native run-android
\+

2018-02-14 10:23 UTC, notxcain approved these changes
:rocket:

2018-02-14 10:29 UTC, merged